- hosts: head
  become: true

  tasks:

    - name: Read variables of 'variables.yml' file
      include_vars:
        file: ../variables.yml
        name: var
    
    - name: HEAD - Clone grafana
      git:
        repo: https://github.com/cloudalchemy/ansible-grafana.git
        dest: /etc/ansible/roles/grafana

    - name: HEAD - Execute role as a task (to maintain order)
      include_role:
        name: grafana
      
    - name: HEAD - Allow port on firewall
      firewalld:
        port: 3000/tcp
        permanent: yes
        state: enabled

    - name: HEAD - Restart firewalld service to apply changes
      systemd:
        name: firewalld
        state: restarted  
  
  ### VARIABLES USER BY GRAFANA ROLE ###      
  vars:
    grafana_security:
      admin_user: root
      admin_password: "{{ var.variables.ROOT_PASSWORD }}"

    grafana_datasources:
      - name: prometheus
        type: prometheus
        access: proxy
        url: 'http://localhost:9090'
        basicAuth: false