- hosts: all
  become: true

  tasks:
    - name: Read variables of 'variables.yml' file
      include_vars:
        file: ../variables.yml
        name: var

    #- name: Disable SELinux
    #  selinux:
    #    state: disabled
  
    - name: Remove selinux
      yum:
        name: selinux*
        state: absent
  
    - name: Encrypt the root password 
      command: "openssl passwd -crypt {{ var.variables.ROOT_PASSWORD }}"
      register: crypted_password

    - name: Change root password
      user: 
        name: root
        update_password: always 
        password: "{{ crypted_password.stdout }}"

    - name: Install spanish locale
      dnf:
        name: glibc-langpack-es
        state: present

    - name: Set timezone
      command: timedatectl set-timezone Europe/Madrid

    #- name: Set locale
    #  command: localectl set-locale LANG=es_ES
    
    - name: Set keymap
      command: localectl set-keymap es

    #- name: Creates /vagrant (new home)
    #  file:
    #    state: directory 
    #    path: /vagrant
    #    owner: vagrant
    #    group: vagrant
    #    mode: 0700

    - name: Copy old home files to new home
      shell: "if [ ! -d /vagrant/.ssh ]; then \
      cp -rp /home/vagrant/.ssh /vagrant; fi"

    #- name: Edit vagrant home (falla al intentar cambiar el usuario en uso)
    #  user:
    #    name: vagrant
    #    home: /vagrant
    #    move_home: yes

    - name: Edit home in /etc/passwd file
      replace: 
        path: /etc/passwd
        regexp: '^vagrant.*$'
        replace: 'vagrant:x:1000:1000::/vagrant:/bin/bash'

    - name: Restart SSHD service to apply changes
      systemd:
        name: sshd
        state: restarted