- hosts: all
  become: true
  
  tasks:
    ### ALL INSTALLATIONS IN EVERY NODE ###
    - name: Install LUA (dependencies)
      package:
        name: "{{ item }}"
        enablerepo: powertools
        state: present
      loop:
        - lua-filesystem
        - lua-posix

    - name: Install lmod, valgrind, GCC and MPIs
      package:
        name: "{{ item }}"
        state: present
      loop:
        - lmod-defaults-gnu9-openmpi4-ohpc
        - mpich-ofi-gnu9-ohpc
        - mvapich2-gnu9-ohpc
        - valgrind-ohpc

    - name: Install Git
      package: 
        name: git 
        state: present

    - name: HEAD - Install sview for Slurm
      package:
        name: "{{ item }}"
        state: present
      loop:
        - xorg-x11-xauth.x86_64
        - slurm-sview-ohpc
        - libcanberra-gtk2.x86_64
      when: ansible_hostname == "head"
