- hosts: all
  become: true

  tasks:
    - name: Encrypt the root's password 
      command: openssl passwd -crypt toor
      register: crypted_password

    - name: Change root password
      user: 
        name: root
        update_password: always 
        password: "{{ crypted_password.stdout }}"

    - name: Change locale and keymap
      command: localectl set-locale LANG=es_ES
    
    - command: localectl set-keymap es

    - name: Disable SELinux
      selinux:
        state: disabled

    #- name: Change permissions for SYNC folder (/vagrant)
    #  file:
    #    path: /vagrant
    #    mode: '0777'
    #    owner: root
    #    group: root