- hosts: computes
  become: true

  tasks:
    - name: Install NFS
      yum: 
        name: nfs-utils.x86_64 
        state: present

    - name: Read variables of 'variables.yml' file
      include_vars:
        file: ../variables.yml
        name: var
    
    - block:
      - name: COMPUTES - Creates custom directory for share
        file:
          path: "{{ var.variables.SHARED_PATH }}"
          state: directory

      - name: COMPUTES - Mount custom shared directory through NFS
        mount:
          src: head:{{ var.variables.SHARED_PATH }}
          path: "{{ var.variables.SHARED_PATH }}"
          opts: rw,sync #,hard,intr,_netdev,retry=1
          state: mounted
          fstype: nfs
      when: var.variables.SHARED_PATH | default('', true) | trim != ''

    - block:
      - name: COMPUTES - Creates default /share directory
        file:
          path: /share
          state: directory

      - name: COMPUTES - Mount default shared directory through NFS
        mount:
          src: head:/share
          path: /share
          opts: rw,sync
          state: mounted
          fstype: nfs
      when: var.variables.SHARED_PATH | default('', true) | trim == ''

    ### IMPORTANT: Mounting head:/home in /home give us an interface ERROR!
    ### To fix, now we mounting in /nfs/home
    - name: COMPUTES - Mount home directory through NFS (users home)
      mount:
        src: head:/home
        path: /nfs/home
        opts: rw,sync
        state: mounted
        fstype: nfs
      #ignore_errors: yes

    - name: Creates an entry to mount by NFS AFTER NETWORK is UP
      cron:
        name: Ping to the HEAD to test network
        special_time: reboot
        job: "until ping -c 1 head; do : ; done && mount -a"