- hosts: computes
  become: true

  tasks:
    - name: Install NFS
      yum: 
        name: nfs-utils.x86_64 
        state: present

    - name: Read variables of 'variables.yml' file
      include_vars:
        file: ../variables.yml
        name: var
    
    - block:
      - name: COMPUTES - Creates custom directory for share
        file:
          path: "{{ var.sharedpath }}"
          state: directory

      - name: COMPUTES - Mount custom shared directory through NFS
        mount:
          src: head:{{ var.sharedpath }}
          path: "{{ var.sharedpath }}"
          opts: rw,sync,hard,intr,_netdev,retry=1
          state: mounted
          fstype: nfs
      when: var.sharedpath | default('', true) | trim != ''

    - block:
      - name: COMPUTES - Creates default /share directory
        file:
          path: /share
          state: directory

      - name: COMPUTES - Mount default shared directory through NFS
        mount:
          src: head:/share
          path: /share
          opts: rw,sync,hard,intr,_netdev,retry=1
          state: mounted
          fstype: nfs
      when: var.sharedpath | default('', true) | trim == ''

    #- name: COMPUTES - Creates directory (/nfs/home)
    #  file:
    #    path: /nfs/home
    #    state: directory

    - name: COMPUTES - Mount home directory through NFS (users home)
      mount:
        src: head:/home
        path: /home
        opts: rw,sync,hard,intr,_netdev,retry=1
        state: mounted
        fstype: nfs
      ignore_errors: yes

    - name: Creates an entry to mount by NFS AFTER NETWORK is UP
      cron:
        name: Ping to the HEAD to test network
        special_time: reboot
        job: "until ping -c 1 head; do : ; done && mount -a"