- hosts: head
  become: true
  
  environment:
    HOME: /vagranthome

  tasks:
    - name: Read vars of variables.yml file
      include_vars:
        file: ../variables.yml
        name: stuff
    
    - name: Set variables LEVEL and DISKS
      set_fact:
        level: "{{ stuff.variables.RAID_LEVEL | default ('', true) }}"
        disks: "{{ stuff.variables.EXTRA_DISKS | default ('', true) }}"

    - name: Install mdadm
      yum: 
        name: mdadm 
        state: present

    # less than 3 disks
    - name: Create RAID 1 (less than 3 disks)
      shell: "if [ ! -f /etc/mdadm.conf ] || [ -s /etc/mdadm.conf ]; then \
      yes | mdadm --create --verbose /dev/md0 --level=1 \
      --raid-devices=2 `ls /dev/sd[b-c]`; fi"
      when: (disks | trim == '') or (disks < "3")
    
    # 3 disks
    - name: Create RAID 1 (3 disks - LEVEL DEFAULT)
      shell: "if [ ! -f /etc/mdadm.conf ] || [ -s /etc/mdadm.conf ]; then \
      yes | mdadm --create --verbose /dev/md0 --level=1 \
      --raid-devices=3 `ls /dev/sd[b-d]`; fi"
      when: 
        - (level | trim == '') or ((level != "1") and (level != "5") and (level != "10")) 
        - disks == "3"

    - name: Create RAID 1/5/10 (3 disks - CUSTOM LEVEL)
      shell: "if [ ! -f /etc/mdadm.conf ] || [ -s /etc/mdadm.conf ]; then \
      yes | mdadm --create --verbose /dev/md0 --level={{ level }} \
      --raid-devices=3 `ls /dev/sd[b-d]`; fi"
      when: 
        - level | trim != ''
        - (level == "1") or (level == "5") or (level == "10") 
        - disks == "3"

    # 4 or more disks
    - name: Create RAID 1 (4 or more disks - LEVEL DEFAULT)
      shell: "if [ ! -f /etc/mdadm.conf ] || [ -s /etc/mdadm.conf ]; then \
      yes | mdadm --create --verbose /dev/md0 --level=1 \
      --raid-devices={{ disks }} `ls /dev/sd[b-z]`; fi"
      when:
        - (level | trim == '') or ((level != "1") and (level != "5") and (level != "6") and (level != "10")) 
        - disks > "3"

    - name: Create RAID 1/5/6/10 (4 or more disks - CUSTOM LEVEL)
      shell: "if [ ! -f /etc/mdadm.conf ] || [ -s /etc/mdadm.conf ]; then \
      yes | mdadm --create --verbose /dev/md0 --level={{ level }} \
      --raid-devices={{ disks }} `ls /dev/sd[b-z]`; fi"
      when:
        - level | trim != ''
        - (level == "1") or (level == "5") or (level == "6") or (level == "10")
        - disks > "3"

    - name: Create file for RAID config
      shell: mdadm --detail --scan > /etc/mdadm.conf

    - name: Create a Volume Group
      lvg:
        vg: vg_raid
        pvs: /dev/md0

    ####### HOME FOLDER ########

    - name: Creates Logical Volumes (/home)
      lvol:
        vg: vg_raid
        lv: lv_home
        size: 50%VG
        pvs: /dev/md0

    - name: Creates filesystem in LV (/home)
      filesystem:
        fstype: xfs
        dev: /dev/mapper/vg_raid-lv_home

    #- name: Save home
    #  copy:
    #    src: /home/vagrant/.ssh
    #    dest: /tmp/
    #    force: yes
    #    directory_mode: yes
      #when: ansible_hostname == "head"

    - name: Mount virtual partition in HOME
      mount:
        src: /dev/mapper/vg_raid-lv_home
        path: /home
        fstype: xfs
        state: mounted 

    #- shell: "mkdir -p /home/vagrant && chown vagrant:vagrant /home/vagrant"
    
    - name: creates /home/vagrant (only for ansible purposes)
      file:
        state: directory 
        path: /home/vagrant/
        recurse: yes
        owner: vagrant
        group: vagrant
    
    #- name: Restore home
    #  shell: "cp -r /tmp/.ssh/* /home/vagrant/.ssh/"

    #- name: Restore home (not work!)
    #  copy: 
    #    src: /tmp/.ssh
    #    dest: /home/vagrant/
    #    force: yes
    #    directory_mode: yes
    #  when: ansible_hostname == "head"
    
    #- name: Change permissions
    #  file:
    #    path: /home/vagrant/
    #    owner: vagrant
    #    group: vagrant
    #    mode: '0700'
    #    recurse: yes

    ####### SHARED FOLDER ########

    - name: Creates Logical Volumes (shared path)
      lvol:
        vg: vg_raid
        lv: lv_share
        size: 50%VG
        pvs: /dev/md0

    - name: Creates filesystem in LV (shared path)
      filesystem:
        fstype: xfs
        dev: /dev/mapper/vg_raid-lv_share

    - block:
      - name: HEAD - Creates custom directory to share
        file:
          path: "{{ stuff.sharedpath }}"
          state: directory

      - name: Mount virtual partition in SHARED FOLDER
        mount:
          src: /dev/mapper/vg_raid-lv_share
          path: "{{ stuff.sharedpath }}"
          fstype: xfs
          state: mounted 
      when: stuff.sharedpath | default('', true) | trim != ''

    - block:
      - name: HEAD - If not specified directory, create default "/share"
        file:
          path: /share
          state: directory    
      
      - name: Mount virtual partition in SHARED FOLDER
        mount:
          src: /dev/mapper/vg_raid-lv_share
          path: /share
          fstype: xfs
          state: mounted
      when: stuff.sharedpath | default('', true) | trim == ''