- hosts: all
  become: true
  
  tasks:
    - name: Read variables of 'variables.yml' file
      include_vars:
        file: ../variables.yml
        name: var

    - name: HEAD - Add several users
      user: 
        name: "{{ item }}"
        state: present
      loop: "{{ var.users }}"
      when: ansible_hostname == "head"

    - name: COMPUTES - Add several users (without /home)
      user: 
        name: "{{ item }}"
        state: present
        create_home: no
      loop: "{{ var.users }}"
      when: ansible_hostname != "head"